name: AirBear OSV
on: [pull_request, workflow_dispatch, schedule]
permissions: { contents: read }
jobs:
  osv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          npm i -g @google/osv-scanner
          osv-scanner scan --lockfile .
